Repository KAU-2024-Sanhak/sanhak, pull requests merged in 2024-11, with the labels that each got.

#64 Refactor: navbar
  src/main/frontend/src/app/card/CardRetrieve.tsx
  src/main/frontend/src/app/card/pageComponents.tsx
  src/main/frontend/src/app/mypage/pageComponents.tsx
  src/main/frontend/src/components/Navbar.tsx
Labels: 🎨 Html&css, 🔨 Refactor

#78 Refactor/ai card api connection
  src/main/frontend/src/app/aiChatbot/ChatInterface.tsx
  src/main/frontend/src/app/card/Card.tsx
  src/main/frontend/src/app/card/CardEditor.tsx
  src/main/frontend/src/app/card/CardRetrieve.tsx
  src/main/frontend/src/app/card/pageComponents.tsx
  src/main/frontend/src/app/category/Roadmap.tsx
  src/main/frontend/src/app/category/TimeLineRoadMap.tsx
  src/main/frontend/src/app/category/pageComponents.tsx
  src/main/frontend/tailwind.config.ts
Labels: 🎨 Html&css, 🔨 Refactor

#102 feat: redesign mypage
  src/main/frontend/.env.local
  src/main/frontend/public/asset/png/card_example_image_4.png
  src/main/frontend/src/app/category/Roadmap.tsx
  src/main/frontend/src/app/globals.css
  src/main/frontend/src/app/mypage/MyPageFilter.tsx
  src/main/frontend/src/app/mypage/RecommendCompany.tsx
  src/main/frontend/src/app/mypage/SkillBadge.tsx
  src/main/frontend/src/app/mypage/UserProfile.tsx
  src/main/frontend/src/app/mypage/pageComponents.tsx
  src/main/frontend/src/models/user.d.ts
Labels: ✨ Feature, 🎨 Html&css, 🔨 Refactor

#104 feat : badge and not login state logic
  readme_asset/Service Architecture.png
  src/main/frontend/.gitignore
  src/main/frontend/src/app/card/CardEditor.tsx
  src/main/frontend/src/app/card/CardRetrieve.tsx
  src/main/frontend/src/app/card/pageComponents.tsx
  src/main/frontend/src/app/careerLounge/page.tsx
  src/main/frontend/src/app/mypage/RoadmapCustomize.tsx
  src/main/frontend/yarn.lock
  src/main/java/com/project/sanhak/aiChatbot/controller/chatController.java
  src/main/java/com/project/sanhak/aiChatbot/repository/chatRepository.java
  src/main/java/com/project/sanhak/aiChatbot/service/chatService.java
  src/main/java/com/project/sanhak/card/controller/cardController.java
  src/main/java/com/project/sanhak/card/service/cardService.java
  src/main/java/com/project/sanhak/category/controller/categoryController.java
  src/main/java/com/project/sanhak/category/service/categoryService.java
  src/main/java/com/project/sanhak/comment/controller/CommentController.java
  src/main/java/com/project/sanhak/company/controller/companyController.java
  src/main/java/com/project/sanhak/company/dto/companyDTO.java
  src/main/java/com/project/sanhak/company/service/companyService.java
  src/main/java/com/project/sanhak/domain/card/ExperienceCard.java
  src/main/java/com/project/sanhak/domain/company/Company.java
  src/main/java/com/project/sanhak/domain/skil/code/PositionCodeSkilConnect.java
  src/main/java/com/project/sanhak/domain/skil/code/PositionCodeSkilConnectId.java
  src/main/java/com/project/sanhak/domain/skil/code/Positions.java
  src/main/java/com/project/sanhak/domain/skil/user/UserRoadmapSkil.java
  src/main/java/com/project/sanhak/domain/user/Profile.java
  src/main/java/com/project/sanhak/login/config/SecurityConfig.java
  src/main/java/com/project/sanhak/login/controller/UserController.java
  src/main/java/com/project/sanhak/lounge/controller/LoungeController.java
  src/main/java/com/project/sanhak/lounge/repository/LoungeLikesRepository.java
  src/main/java/com/project/sanhak/lounge/service/LoungeService.java
  src/main/java/com/project/sanhak/main/controller/MainController.java
  src/main/java/com/project/sanhak/main/dto/cardDTO.java
  src/main/java/com/project/sanhak/main/repository/ProfileRepository.java
  src/main/java/com/project/sanhak/main/service/MainService.java
  src/main/java/com/project/sanhak/main/service/ProfileService.java
  src/main/java/com/project/sanhak/mypage/controller/MypageController.java
  src/main/java/com/project/sanhak/mypage/dto/badgeDTO.java
  src/main/java/com/project/sanhak/mypage/dto/changeRoadmapDTO.java
  src/main/java/com/project/sanhak/mypage/dto/roadmapDTO.java
  src/main/java/com/project/sanhak/mypage/repository/BadgeRepository.java
  src/main/java/com/project/sanhak/mypage/repository/MypageRepository.java
  src/main/java/com/project/sanhak/mypage/repository/RoadmapRepository.java
  src/main/java/com/project/sanhak/mypage/repository/RoadmapSkilPrequeRepository.java
  src/main/java/com/project/sanhak/mypage/repository/UserMasterySkilRepository.java
  src/main/java/com/project/sanhak/mypage/service/MypageService.java
  src/main/java/com/project/sanhak/util/s3/S3FileService.java
  src/main/java/com/project/sanhak/util/swaggerConfig.java
  src/main/resources/application.properties
Labels: 🐞 BugFix, 🌏 Deploy, 📬 API, 🔨 Refactor, 🥰 Accessibility

#105 Pr merge
  readme_asset/Service Architecture.png
  src/main/frontend/.gitignore
  src/main/frontend/src/app/card/CardEditor.tsx
  src/main/frontend/src/app/card/CardRetrieve.tsx
  src/main/frontend/src/app/card/pageComponents.tsx
  src/main/frontend/src/app/careerLounge/page.tsx
  src/main/frontend/src/app/mypage/RoadmapCustomize.tsx
  src/main/frontend/yarn.lock
  src/main/java/com/project/sanhak/aiChatbot/controller/chatController.java
  src/main/java/com/project/sanhak/aiChatbot/repository/chatRepository.java
  src/main/java/com/project/sanhak/aiChatbot/service/chatService.java
  src/main/java/com/project/sanhak/card/controller/cardController.java
  src/main/java/com/project/sanhak/card/service/cardService.java
  src/main/java/com/project/sanhak/category/controller/categoryController.java
  src/main/java/com/project/sanhak/category/service/categoryService.java
  src/main/java/com/project/sanhak/comment/controller/CommentController.java
  src/main/java/com/project/sanhak/company/controller/companyController.java
  src/main/java/com/project/sanhak/company/dto/companyDTO.java
  src/main/java/com/project/sanhak/company/service/companyService.java
  src/main/java/com/project/sanhak/domain/card/ExperienceCard.java
  src/main/java/com/project/sanhak/domain/company/Company.java
  src/main/java/com/project/sanhak/domain/skil/code/PositionCodeSkilConnect.java
  src/main/java/com/project/sanhak/domain/skil/code/PositionCodeSkilConnectId.java
  src/main/java/com/project/sanhak/domain/skil/code/Positions.java
  src/main/java/com/project/sanhak/domain/skil/user/UserRoadmapSkil.java
  src/main/java/com/project/sanhak/domain/user/Profile.java
  src/main/java/com/project/sanhak/login/config/SecurityConfig.java
  src/main/java/com/project/sanhak/login/controller/UserController.java
  src/main/java/com/project/sanhak/lounge/controller/LoungeController.java
  src/main/java/com/project/sanhak/lounge/repository/LoungeLikesRepository.java
  src/main/java/com/project/sanhak/lounge/service/LoungeService.java
  src/main/java/com/project/sanhak/main/controller/MainController.java
  src/main/java/com/project/sanhak/main/dto/cardDTO.java
  src/main/java/com/project/sanhak/main/repository/ProfileRepository.java
  src/main/java/com/project/sanhak/main/service/MainService.java
  src/main/java/com/project/sanhak/main/service/ProfileService.java
  src/main/java/com/project/sanhak/mypage/controller/MypageController.java
  src/main/java/com/project/sanhak/mypage/dto/badgeDTO.java
  src/main/java/com/project/sanhak/mypage/dto/changeRoadmapDTO.java
  src/main/java/com/project/sanhak/mypage/dto/roadmapDTO.java
  src/main/java/com/project/sanhak/mypage/repository/BadgeRepository.java
  src/main/java/com/project/sanhak/mypage/repository/MypageRepository.java
  src/main/java/com/project/sanhak/mypage/repository/RoadmapRepository.java
  src/main/java/com/project/sanhak/mypage/repository/RoadmapSkilPrequeRepository.java
  src/main/java/com/project/sanhak/mypage/repository/UserMasterySkilRepository.java
  src/main/java/com/project/sanhak/mypage/service/MypageService.java
  src/main/java/com/project/sanhak/util/s3/S3FileService.java
  src/main/java/com/project/sanhak/util/swaggerConfig.java
  src/main/resources/application.properties
Labels: merge

#107 Pr merge
  src/main/frontend/src/app/page.tsx
  src/main/java/com/project/sanhak/card/controller/cardController.java
  src/main/java/com/project/sanhak/login/controller/UserController.java
  src/main/java/com/project/sanhak/main/controller/MainController.java
  src/main/java/com/project/sanhak/main/repository/OAuthTokenRepository.java
  src/main/java/com/project/sanhak/main/repository/UserRepository.java
  src/main/java/com/project/sanhak/mypage/controller/MypageController.java
Labels: merge

#108 fix : error in the ai card part
  src/main/java/com/project/sanhak/card/service/cardService.java
  src/main/java/com/project/sanhak/mypage/service/MypageService.java
Labels: 🐞 BugFix, 📬 API

#113 Feat/custom roadmap page
  src/main/frontend/public/asset/png/icon_arrow_down.png
  src/main/frontend/public/asset/png/icon_arrow_up.png
  src/main/frontend/src/app/careerLounge/page.tsx
  src/main/frontend/src/app/category/Roadmap.tsx
  src/main/frontend/src/app/customRoadmap/CustomRoadmapList.tsx
  src/main/frontend/src/app/customRoadmap/CustomSkillList.tsx
  src/main/frontend/src/app/customRoadmap/page.tsx
  src/main/frontend/src/app/customRoadmap/pageComponent.tsx
  src/main/frontend/src/app/mypage/RoadmapCustomize.tsx
  src/main/frontend/src/app/mypage/pageComponents.tsx
  src/main/frontend/src/components/Navbar.tsx
  src/main/frontend/src/models/roadmap.d.ts
  src/main/frontend/src/models/user.d.ts
Labels: ✨ Feature, 🎨 Html&css

#116 Feat/lounge page api connection
  src/main/frontend/src/app/lounge/MiniProfile.tsx
  src/main/frontend/src/app/lounge/pageComponents.tsx
  src/main/frontend/src/models/user.d.ts
  src/main/java/com/project/sanhak/lounge/service/LoungeService.java
Labels: 🐞 BugFix, ✨ Feature, 📬 API

#117 refactor : profile controller code, roadmap logic
  src/main/frontend/src/app/aiChatbot/ChatInterface.tsx
  src/main/frontend/src/app/aiChatbot/pageComponents.tsx
  src/main/frontend/src/app/lounge/MiniProfile.tsx
  src/main/frontend/src/app/lounge/pageComponents.tsx
  src/main/frontend/src/app/main/BodySectionComponents.tsx
  src/main/frontend/src/app/main/HeadSectionComponents.tsx
  src/main/frontend/src/models/card.d.ts
  src/main/frontend/src/models/user.d.ts
  src/main/java/com/project/sanhak/domain/card/ExperienceCard.java
  src/main/java/com/project/sanhak/domain/skil/code/PositionCodeSkilConnect.java
  src/main/java/com/project/sanhak/domain/skil/code/PositionCodeSkilConnectId.java
  src/main/java/com/project/sanhak/domain/skil/code/Positions.java
  src/main/java/com/project/sanhak/domain/user/Profile.java
  src/main/java/com/project/sanhak/login/service/OAuth2Service.java
  src/main/java/com/project/sanhak/lounge/service/LoungeService.java
  src/main/java/com/project/sanhak/main/controller/MainController.java
  src/main/java/com/project/sanhak/main/dto/profileDTO.java
  src/main/java/com/project/sanhak/main/service/ProfileService.java
  src/main/java/com/project/sanhak/mypage/controller/MypageController.java
  src/main/java/com/project/sanhak/mypage/repository/RoadmapRepository.java
  src/main/java/com/project/sanhak/mypage/service/MypageService.java
Labels: 🔨 Refactor

#119 Feat/mypage crud api connection
  src/main/frontend/public/asset/png/icon_modify_profile.png
  src/main/frontend/public/asset/png/profile_default_image.png
  src/main/frontend/src/app/mypage/UserProfile.tsx
  src/main/frontend/src/app/mypage/pageComponents.tsx
  src/main/frontend/src/models/user.d.ts
Labels: ✨ Feature, 🎨 Html&css, 📬 API

#123 Refactor/mypage mobile UI
  src/main/frontend/src/app/mypage/RecommendCompany.tsx
  src/main/frontend/src/app/mypage/UserProfile.tsx
  src/main/frontend/src/app/mypage/pageComponents.tsx
  src/main/frontend/tailwind.config.ts
Labels: 🎨 Html&css

#126 refactor/navbar-and-mypage-mobile-ui
  src/main/frontend/public/asset/png/icon_company.png
  src/main/frontend/public/asset/png/icon_side_menu.png
  src/main/frontend/src/app/card/Card.tsx
  src/main/frontend/src/app/mypage/RecommendCompany.tsx
  src/main/frontend/src/app/mypage/SkillBadge.tsx
  src/main/frontend/src/app/mypage/UserProfile.tsx
  src/main/frontend/src/app/mypage/pageComponents.tsx
  src/main/frontend/src/components/Navbar.tsx
  src/main/frontend/tailwind.config.ts
Labels: 🎨 Html&css

#127 Pr merge
  src/main/frontend/public/asset/png/icon_company.png
  src/main/frontend/public/asset/png/icon_side_menu.png
  src/main/frontend/src/app/card/Card.tsx
  src/main/frontend/src/app/card/CardEditor.tsx
  src/main/frontend/src/app/customRoadmap/pageComponent.tsx
  src/main/frontend/src/app/main/BodySectionComponents.tsx
  src/main/frontend/src/app/main/HeadSectionComponents.tsx
  src/main/frontend/src/app/main/pageComponents.tsx
  src/main/frontend/src/app/mypage/RecommendCompany.tsx
  src/main/frontend/src/app/mypage/SkillBadge.tsx
  src/main/frontend/src/app/mypage/UserProfile.tsx
  src/main/frontend/src/app/mypage/pageComponents.tsx
  src/main/frontend/src/components/Navbar.tsx
  src/main/frontend/src/models/roadmap.d.ts
  src/main/frontend/src/models/user.d.ts
  src/main/frontend/tailwind.config.ts
  src/main/java/com/project/sanhak/card/controller/cardController.java
  src/main/java/com/project/sanhak/card/service/cardService.java
  src/main/java/com/project/sanhak/category/repository/categoryRepository.java
  src/main/java/com/project/sanhak/category/service/categoryService.java
  src/main/java/com/project/sanhak/domain/board/BoardLikes.java
  src/main/java/com/project/sanhak/domain/board/BoardReport.java
  src/main/java/com/project/sanhak/domain/board/Boards.java
  src/main/java/com/project/sanhak/domain/chat/ChatRooms.java
  src/main/java/com/project/sanhak/domain/comment/CommentLikes.java
  src/main/java/com/project/sanhak/domain/comment/CommentReport.java
  src/main/java/com/project/sanhak/domain/comment/Comments.java
  src/main/java/com/project/sanhak/domain/mentor/Mentors.java
  src/main/java/com/project/sanhak/domain/skil/code/CodeSkil.java
  src/main/java/com/project/sanhak/domain/skil/code/PositionCodeSkilConnect.java
  src/main/java/com/project/sanhak/domain/skil/code/PositionCodeSkilConnectId.java
  src/main/java/com/project/sanhak/domain/skil/code/Positions.java
  src/main/java/com/project/sanhak/domain/skil/code/SkilPreque.java
  src/main/java/com/project/sanhak/domain/skil/code/SkilPrequeCateFlags.java
  src/main/java/com/project/sanhak/domain/skil/code/cateFlag.java
  src/main/java/com/project/sanhak/domain/user/Profile.java
  src/main/java/com/project/sanhak/login/service/OAuth2Service.java
  src/main/java/com/project/sanhak/main/controller/MainController.java
  src/main/java/com/project/sanhak/mypage/controller/MypageController.java
  src/main/java/com/project/sanhak/mypage/dto/changeRoadmapDTO.java
  src/main/java/com/project/sanhak/mypage/dto/mergeRoadmapDTO.java
  src/main/java/com/project/sanhak/mypage/service/MypageService.java
Labels: merge

#128 error : custom roadmap node can't move.
  README.md
  readme_asset/Service Architecture.png
  readme_asset/db.png
  src/main/frontend/src/app/customRoadmap/pageComponent.tsx
  src/main/frontend/src/models/roadmap.d.ts
  src/main/java/com/project/sanhak/domain/skil/user/UserRoadmapSkilPreque.java
  src/main/java/com/project/sanhak/mypage/controller/MypageController.java
  src/main/java/com/project/sanhak/mypage/dto/changeRoadmapDTO.java
  src/main/java/com/project/sanhak/mypage/dto/roadmapUpdateRequest.java
  src/main/java/com/project/sanhak/mypage/repository/RoadmapSkilPrequeRepository.java
  src/main/java/com/project/sanhak/mypage/repository/RoadmapSkilRepository.java
  src/main/java/com/project/sanhak/mypage/service/MypageService.java
Labels: 📬 API

#129 Refactor/career lounge mobile UI
  src/main/frontend/src/app/layout.tsx
  src/main/frontend/src/app/lounge/LoungeFilter.tsx
  src/main/frontend/src/app/lounge/MiniProfile.tsx
  src/main/frontend/src/app/lounge/pageComponents.tsx
  src/main/frontend/src/app/mypage/RecommendCompany.tsx
  src/main/frontend/src/app/mypage/pageComponents.tsx
  src/main/frontend/src/app/page.tsx
  src/main/frontend/src/app/userCareer/page.tsx
  src/main/frontend/src/app/userCareer/pageComponents.tsx
  src/main/frontend/src/components/Navbar.tsx
  src/main/frontend/src/context/UserContext.tsx
  src/main/frontend/src/models/user.d.ts
Labels: 🐞 BugFix, ✨ Feature, 🎨 Html&css, 📬 API, 🔨 Refactor

#130 Pr merge
  README.md
  readme_asset/Service Architecture.png
  readme_asset/db.png
  src/main/frontend/src/app/customRoadmap/pageComponent.tsx
  src/main/frontend/src/app/layout.tsx
  src/main/frontend/src/app/lounge/LoungeFilter.tsx
  src/main/frontend/src/app/lounge/MiniProfile.tsx
  src/main/frontend/src/app/lounge/pageComponents.tsx
  src/main/frontend/src/app/mypage/RecommendCompany.tsx
  src/main/frontend/src/app/mypage/pageComponents.tsx
  src/main/frontend/src/app/page.tsx
  src/main/frontend/src/app/userCareer/page.tsx
  src/main/frontend/src/app/userCareer/pageComponents.tsx
  src/main/frontend/src/components/Navbar.tsx
  src/main/frontend/src/context/UserContext.tsx
  src/main/frontend/src/models/roadmap.d.ts
  src/main/frontend/src/models/user.d.ts
  src/main/java/com/project/sanhak/domain/skil/user/UserRoadmapSkilPreque.java
  src/main/java/com/project/sanhak/mypage/controller/MypageController.java
  src/main/java/com/project/sanhak/mypage/dto/changeRoadmapDTO.java
  src/main/java/com/project/sanhak/mypage/dto/roadmapUpdateRequest.java
  src/main/java/com/project/sanhak/mypage/repository/RoadmapSkilPrequeRepository.java
  src/main/java/com/project/sanhak/mypage/repository/RoadmapSkilRepository.java
  src/main/java/com/project/sanhak/mypage/service/MypageService.java
Labels: merge

#132 feat : Mastery Skill Sidebar, Skill Learning Action Confirmed.
  src/main/frontend/src/app/category/Roadmap.tsx
  src/main/frontend/src/app/category/SkillNode.tsx
  src/main/frontend/src/app/category/pageComponents.tsx
  src/main/frontend/src/app/customRoadmap/QuizModal.tsx
  src/main/frontend/src/app/customRoadmap/SkillDetailModal.tsx
  src/main/frontend/src/app/customRoadmap/pageComponent.tsx
  src/main/frontend/src/app/lounge/pageComponents.tsx
  src/main/frontend/src/app/mypage/RoadmapCustomize.tsx
  src/main/frontend/src/app/mypage/UserProfile.tsx
  src/main/frontend/src/models/skill.d.ts
  src/main/java/com/project/sanhak/category/repository/categoryRepository.java
  src/main/java/com/project/sanhak/login/repository/AuthRepository.java
  src/main/java/com/project/sanhak/lounge/controller/LoungeController.java
  src/main/java/com/project/sanhak/lounge/dto/LoungesDTO.java
  src/main/java/com/project/sanhak/lounge/repository/LoungeRepository.java
  src/main/java/com/project/sanhak/lounge/service/LoungeService.java
  src/main/java/com/project/sanhak/main/service/ProfileService.java
  src/main/java/com/project/sanhak/mypage/controller/MypageController.java
  src/main/java/com/project/sanhak/mypage/dto/masteryDTO.java
  src/main/java/com/project/sanhak/mypage/dto/mergeMasteryDTO.java
  src/main/java/com/project/sanhak/mypage/service/MypageService.java
Labels: 🐞 BugFix, ✨ Feature, 🎨 Html&css, 📬 API, 🔨 Refactor
