Repository KAU-2024-Sanhak/sanhak, pull requests merged in 2024-12, with the labels that each got.

#136 refactor: ai-card-page-mobile-ui
  src/main/frontend/src/app/card/Card.tsx
  src/main/frontend/src/app/card/CardEditor.tsx
  src/main/frontend/src/app/card/CardEditorFormSection.tsx
  src/main/frontend/src/app/card/CardRetrieve.tsx
  src/main/frontend/src/app/card/pageComponents.tsx
  src/main/frontend/src/app/mypage/pageComponents.tsx
  src/main/frontend/src/components/ButtonLabel.tsx
Labels: ✨ Feature, 🎨 Html&css, 🔨 Refactor

#138 Fix/login auth status
  .DS_Store
  src/.DS_Store
  src/main/frontend/.env.local
  src/main/frontend/next.config.js
  src/main/frontend/public/asset/png/mainpage/mockup_category.png
  src/main/frontend/public/asset/png/mainpage/timelineroadmap_backend.png
  src/main/frontend/public/asset/png/mainpage/timelineroadmap_datascience.png
  src/main/frontend/public/asset/png/mainpage/timelineroadmap_frontend.png
  src/main/frontend/public/asset/png/mainpage/timelineroadmap_security.png
  src/main/frontend/src/app/careerLounge/page.tsx
  src/main/frontend/src/app/main/BodySectionComponents.tsx
  src/main/frontend/src/app/main/HeadSectionComponents.tsx
  src/main/frontend/tsconfig.json
  src/main/java/com/project/sanhak/company/repository/companyReqRepository.java
  src/main/java/com/project/sanhak/company/repository/companyReqSkilRepository.java
  src/main/java/com/project/sanhak/domain/company/ComComReqConnect.java
  src/main/java/com/project/sanhak/domain/company/CompanyReq.java
  src/main/java/com/project/sanhak/domain/company/CompanyReqSkil.java
  src/main/java/com/project/sanhak/login/controller/UserController.java
Labels: 🐞 BugFix, 📬 API, 🔨 Refactor

#140 feat : Keep lounge filters, filters and user profiles when refreshing…
  src/main/frontend/src/app/customRoadmap/pageComponent.tsx
  src/main/frontend/src/app/lounge/LoungeFilter.tsx
  src/main/frontend/src/app/lounge/pageComponents.tsx
  src/main/frontend/src/app/mypage/UserProfile.tsx
  src/main/frontend/src/app/mypage/pageComponents.tsx
  src/main/frontend/src/app/userCareer/pageComponents.tsx
  src/main/java/com/project/sanhak/mypage/controller/MypageController.java
  src/main/java/com/project/sanhak/mypage/dto/mergeRoadmapDTO.java
  src/main/java/com/project/sanhak/mypage/service/MypageService.java
Labels: 🐞 BugFix, ✨ Feature, 📬 API, 🔨 Refactor

#141 refactor: category-roamap-page-mobile-ui
  src/main/frontend/src/app/category/CategoryButton.tsx
  src/main/frontend/src/app/category/TimeLineRoadMap.tsx
  src/main/frontend/src/app/category/pageComponents.tsx
  src/main/frontend/src/app/customRoadmap/SkillDetailModal.tsx
  src/main/frontend/src/app/mypage/UserProfile.tsx
  src/main/frontend/src/app/mypage/pageComponents.tsx
  src/main/frontend/src/components/Navbar.tsx
Labels: ✨ Feature, 🎨 Html&css, 🔨 Refactor

#145 Refactor/aichat page mobile UI
  src/main/frontend/.env.local
  src/main/frontend/package.json
  src/main/frontend/public/asset/png/icon_list_close.png
  src/main/frontend/public/asset/png/icon_list_open.png
  src/main/frontend/src/app/aiChatbot/ChatInterface.tsx
  src/main/frontend/src/app/aiChatbot/ChatRoleDropdown.tsx
  src/main/frontend/src/app/aiChatbot/ChatRoomList.tsx
  src/main/frontend/src/app/aiChatbot/pageComponents.tsx
  src/main/frontend/src/components/Navbar.tsx
Labels: ✨ Feature, 🎨 Html&css, 🔨 Refactor

#151 refactor: custom-roadmap-mobile-ui
  src/main/frontend/src/app/aiChatbot/pageComponents.tsx
  src/main/frontend/src/app/customRoadmap/CustomRoadmapList.tsx
  src/main/frontend/src/app/customRoadmap/CustomSkillList.tsx
  src/main/frontend/src/app/customRoadmap/pageComponent.tsx
Labels: ✨ Feature, 🎨 Html&css, 🔨 Refactor

#161 Fix/UI detail fix 2
  src/main/frontend/public/asset/png/icon_chat_send.png
  src/main/frontend/src/app/aiChatbot/ChatInterface.tsx
  src/main/frontend/src/app/aiChatbot/ChatRoomList.tsx
  src/main/frontend/src/app/aiChatbot/pageComponents.tsx
  src/main/frontend/src/app/card/Card.tsx
  src/main/frontend/src/app/card/CardEditor.tsx
  src/main/frontend/src/app/card/CardRetrieve.tsx
  src/main/frontend/src/app/category/pageComponents.tsx
  src/main/frontend/src/app/customRoadmap/CustomRoadmapList.tsx
  src/main/frontend/src/app/customRoadmap/CustomSkillList.tsx
  src/main/frontend/src/app/customRoadmap/QuizModal.tsx
  src/main/frontend/src/app/customRoadmap/SkillDetailModal.tsx
  src/main/frontend/src/app/customRoadmap/pageComponent.tsx
  src/main/frontend/src/app/lounge/LoungeFilter.tsx
  src/main/frontend/src/app/lounge/pageComponents.tsx
  src/main/frontend/src/app/mypage/UserProfile.tsx
  src/main/frontend/src/components/ButtonLabel.tsx
  src/main/frontend/src/models/card.d.ts
Labels: 🐞 BugFix, 🎨 Html&css, 🔨 Refactor

#163 Fix/aichat card select error
  src/main/frontend/src/app/aiChatbot/ChatRoomList.tsx
Labels: 🐞 BugFix

#169 Fix/UI detail
  src/main/frontend/src/app/customRoadmap/CustomRoadmapList.tsx
  src/main/frontend/src/app/mypage/pageComponents.tsx
Labels: 🐞 BugFix
